### ISSUE TITLE
npm install fails with ERESOLVE overriding peer dependency for @mintplayer/ng-player-progress 

### ISSUE THREAD

**Issue by VilleFTW** [MintPlayer/mintplayer-ng-video-player#65]
**Describe the bug**
 When running `npm install`, the process fails with an `ERESOLVE overriding peer dependency` warning and an `ETARGET no matching version found` error for `@mintplayer/ng-player-progress@^17.3.0`.

**To Reproduce**
1. Run `npm install`
2. See error

**Expected behavior**
`npm install` should complete without errors.

**Error log**

`npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @mintplayer/player-provider@17.3.0
npm WARN Found: @mintplayer/ng-player-progress@undefined
npm WARN node_modules/@mintplayer/ng-player-progress
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @mintplayer/ng-player-progress@"^17.3.0" from @mintplayer/player-provider@17.3.0
npm WARN node_modules/@mintplayer/player-provider
npm WARN   peer @mintplayer/player-provider@"^17.3.0" from @mintplayer/ng-video-player@17.3.9
npm WARN   node_modules/@mintplayer/ng-video-player
npm WARN   1 more (@mintplayer/video-player)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mintplayer/ng-player-progress@^17.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

**Environment (please complete the following information):**
- Node.js version: [e.g. 18.20.2]
- npm version: [e.g. 10.5.0]

**Additional context**
Add any other context about the problem here. Initially, I discovered this bug while doing an `npx npm-check-updates` routine. I've noticed a bump from v17 to 17.3.0. After modifying the version to 17.3, and running another `npm install`, I get the following error
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mintplayer/ng-vimeo-player@17.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

**Comment by PieterjanDeClippel** [comment]
Thanks for reporting. The issue should be fixed now after the workflow completes
